version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    cooldown:
      default-days: 7
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
    open-pull-requests-limit: 3
  - package-ecosystem: npm
    directory: /
    target-branch: develop
    cooldown:
      default-days: 7
    schedule:
      interval: weekly
    groups:
      react-native:
        patterns:
          [
            'react-native*',
            '@react-native/*',
            '@react-native-community/*',
            '@testing-library/react-native',
            'react-test-renderer',
            'react',
            'react-dom',
            '@types/react*',
          ]
      nest-prisma:
        patterns: ['@nestjs/*', 'prisma', '@prisma/*']
      tooling:
        patterns: ['eslint*', 'typescript*', 'turbo', 'prettier', 'lint-staged']
    open-pull-requests-limit: 5
